"on":
    push:
        branches:
            - master
name: Deploy to calculator-frontend
jobs:
    porter-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Set Github tag
              id: vars
              run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
            - name: Setup porter
              uses: porter-dev/setup-porter@v0.1.0
            - name: Deploy stack
              timeout-minutes: 30
              run: exec porter apply -f porter.yaml
              env:
                PORTER_APP_NAME: calculator-frontend
                PORTER_CLUSTER: "1"
                PORTER_DEPLOYMENT_TARGET_ID: 1cd06bf8-e7af-4611-bcfb-4d04ebb5ae7a
                PORTER_HOST: https://witt.withporter.run
                PORTER_PR_NUMBER: ${{ github.event.number }}
                PORTER_PROJECT: "1"
                PORTER_REPO_NAME: ${{ github.event.repository.name }}
                PORTER_TAG: ${{ steps.vars.outputs.sha_short }}
                PORTER_TOKEN: ${{ secrets.PORTER_APP_1_1 }}
